 export const Zones = [
    { "id": 1, "name": "Gimonde" },
    { "id": 2, "name": "Santa-Maria" },
    { "id": 3, "name": "Samil" },
    { "id": 4, "name": "Sé" },
    { "id": 5, "name": "Crijó de Parada" },
    { "id": 6, "name": "S.Pedro de Sarracenos" },
    { "id": 7, "name": "Nogueira" },
    { "id": 8, "name": "Izeda" },
    { "id": 9, "name": "Pinela" },
    { "id": 10, "name": "Castro de Avelãs" },
    { "id": 11, "name": "França" },
    { "id": 12, "name": "Sortes" },
    { "id": 13, "name": "Pombares" },
    { "id": 14, "name": "Rebordãos" },
    { "id": 15, "name": "Babe" },
    { "id": 16, "name": "Quintela de Lampas" },
    { "id": 17, "name": "Coelhoso " },
    { "id": 18, "name": "Outeiro" },
    { "id": 19, "name": "Salsas" },
    { "id": 20, "name": "Aveleda" },
    { "id": 21, "name": "Rio Frio" },
    { "id": 22, "name": "Parada" },
    { "id": 23, "name": "Espinhosela" },
    { "id": 24, "name": "Carragosa" },
    { "id": 25, "name": "Meixedo" },
    { "id": 26, "name": "Castrelos" },
    { "id": 27, "name": "Zoio" },
    { "id": 28, "name": "Faílde" },
    { "id": 29, "name": "Rabal" },
    { "id": 30, "name": "S.Julião de Palacios" },
    { "id": 31, "name": "Deilão" },
    { "id": 32, "name": "Rio de Onor" },
    { "id": 33, "name": "Alfaião" },
    { "id": 34, "name": "Baçal" },
    { "id": 35, "name": "Santa Comba de Rossas" },
    { "id": 36, "name": "Gostei" },
    { "id": 37, "name": "Paradinha Nova" },
    { "id": 38, "name": "Serapicos" },
    { "id": 39, "name": "Mós" },
    { "id": 40, "name": "Sendas" },
    { "id": 41, "name": "Milhão" },
    { "id": 42, "name": "Donai" },
    { "id": 43, "name": "Macedo de Mato" },
    { "id": 44, "name": "Quintanilha" },
    { "id": 45, "name": "Carrazedo" },
    { "id": 46, "name": "Condesende" },
    { "id": 47, "name": "Rebordaínhos" },
    { "id": 48, "name": "Calvelhe" },
    { "id": 49, "name": "Parâmio" }
]

export const ConsumerType = [
    { "id": 1, "name": "DOMÉSTICO" },
    { "id": 2, "name": "COM/INDUSTRIAL/OBRAS" },
    { "id": 3, "name": "UTIL.PUBLICA" },
    { "id": 4, "name": "OBRAS" },
    { "id": 5, "name": "ESTADO" },
    { "id": 6, "name": "IGREJAS" },
    { "id": 7, "name": "EXP.A.RURAL" },
    { "id": 8, "name": "RURAL DOMÉSTICO" },
    { "id": 9, "name": "RURAL/ESTADO" },
    { "id": 10, "name": "FAM.NUMEROSAS" },
    { "id": 11, "name": "FAM.CARENCIADAS" },
    { "id": 12, "name": "NUMER./CARENC." },
    { "id": 13, "name": "CP.DOM/URB" },
    { "id": 14, "name": "CP.COM/URB" },
    { "id": 15, "name": "CP.DOM/RURAL" },
    { "id": 16, "name": "CP.COM/RURAL" },
    { "id": 17, "name": "IPSS/IGR/RURAL" },
    { "id": 18, "name": "DOM./RURAL A.S" },
    { "id": 19, "name": "COM./RURAL A.S" },
    { "id": 20, "name": "REGA" },
    { "id": 21, "name": "CMB" }
]


export const Months = [
    { "id": 1, "name": "January" },
    { "id": 2, "name": "February" },
    { "id": 3, "name": "March" },
    { "id": 4, "name": "April" },
    { "id": 5, "name": "May" },
    { "id": 6, "name": "June" },
    { "id": 7, "name": "July" },
    { "id": 8, "name": "August" },
    { "id": 9, "name": "September" },
    { "id": 10, "name": "October" },
    { "id": 11, "name": "November" },
    { 'id': 12, "name": "December" }
]
